export const GET_STOCK_LIST = 'GET_STOCK_LIST';
export const UPDATE_STOCK_LIST = 'UPDATED_STOCK_LIST';
export const DELETE_ITEM_FROM_LIST = 'DELETE_ITEM_FROM_LIST';
export const COMPLETE_ITEM_FROM_LIST = 'COMPLETE_ITEM_FROM_LIST';
export const NO_STOCK_FOR_ITEM = 'NO_STOCK_FOR_ITEM';
export const LAST_STOCK_FOR_ITEM = 'LAST_STOCK_FOR_ITEM';

export const ADD_TO_QUEUE = 'ADD_TO_QUEUE';