export const GET_ALL_CATERGORIES = 'GET_ALL_CATERGORIES';
export const GET_STYLES_BY_CATEGORY_ID = "GET_STYLES_BY_CATEGORY_ID";
export const GET_SHOES_BY_SHOESTYLE_ID = 'GET_SHOES_BY_SHOESTYLE_ID';
export const SUBMIT_SHOE_REQUEST_BY_ID = "SUBMIT_SHOE_REQUEST_BY_ID";
