export const GET_FLOOR_DATA = 'GET_FLOOR_DATA';
export const GET_STYLES_BY_CATEGORY_ID = "GET_STYLES_BY_CATEGORY_ID";
export const GET_SHOES_BY_SHOESTYLE_ID = 'GET_SHOES_BY_SHOESTYLE_ID';
export const SUBMIT_SHOE_REQUEST_BY_ID = "SUBMIT_SHOE_REQUEST_BY_ID";
